const express = require('express');
const authenticate = require('../middlewares/authenticate');
const managerController = require('../controllers/managerController');
const router = express.Router();

// router.get('/myinfor/:user_id', authenticate,authController.getUserById);
router.get('/listGuard', managerController.getListGuard);
router.get('/listGuardFree', managerController.getListGuardFree);
router.get('/listCustomer', managerController.getListCustomer);
router.get('/getAllBooking',managerController.getAllBooking);
router.get('/getDetailBooking/:bookingname', managerController.getDetailBooking);
router.get('/getBookingPayment', managerController.getBookingPayment);
router.get('/getBookingNotPayment', managerController.getBookingNotPayment);
router.get('/getBookingDone', managerController.getBookingDone);
router.get('/getGuardbyBookingname/:bookingname',managerController.getGuardbyBookingname);
router.get('/GetSalaryGuard/:guard_id',managerController.GetSalaryGuard);
router.get('/getCustomerById/:customer_id', managerController.getCustomerById);
router.get('/getGuardById/:guard_id', managerController.getGuardById);
router.get('/getAllNews', managerController.getAllNews);
router.get('/getTop4News', managerController.getTop4News);
router.get('/getDetailNews/:news_id', managerController.getDetailNews);
router.post('/PickGuard/:bookingname', managerController.PickGuard);
router.post('/postEnoughGuard/:bookingname', managerController.postEnoughGuard);
router.post('/EditGuardBooking/:bookingname', managerController.EditGuardBooking);
router.post('/postNews', managerController.postNews);
router.post('/editNews', managerController.editNews);
router.post('/deleteNews/:news_id', managerController.deleteNews);
router.get('/dashboard/summary', managerController.summary);
router.get('/searchGuard', managerController.SearchGuard);
router.get('/searchCustomer', managerController.SearchCustomer);
router.get('/filterByStatus', managerController.filterByStatus);
router.get('/getMyNoti',managerController.getMyNoti)
module.exports = router;